version: "3.6"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
#     device: /Users/${USER}/Desktop/Inception/srcs/mariadb
      device: /home/${USER}/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
