version: "3.9"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb/
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress/

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_WP_NAME=${DB_WP_NAME}
        - DB_WP_USER=${DB_WP_USER}
        - DB_WP_PASS=${DB_WP_PASS}
        - DB_ROOT_PASS=${DB_ROOT_PASS}
    image: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - WP_TITLE=${WP_TITLE}
        - WP_USER=${WP_USER}
        - WP_PWD=${WP_PWD}
        - WP_EMAIL=${WP_EMAIL}
        - DB_WP_NAME=${DB_WP_NAME}
        - DB_WP_PASS=${DB_WP_PASS}
        - DB_WP_USER=${DB_WP_USER}
        - DB_WP_PORT=${DB_WP_PORT}
        - WP_ADMIN_USER=${WP_ADMIN_USER}
        - WP_ADMIN_PWD=${WP_ADMIN_PWD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://mroy.42.fr/wp-admin/"]
      interval: 5s
      timeout: 3s
      retries: 3
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "https://mroy.42.fr/"]
      interval: 5s
      timeout: 3s
      retries: 3
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - inception 
    ports:
      - 443:443
    restart: unless-stopped
